version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package_manager: "python"
    directory: "/"
    schedule:
      interval: "live"
    update_schedule: "live"
  - package_manager: "terraform"
    directory: "/"
    schedule:
      interval: "live"
