---
_extends: gh-plumbing:.github/commons-settings.yml

repository:
  name: ansible_playbook-baseline-online-server
  description: Bootstrapping server, install a set of common tools and configurations.
  homepage: https://nolte.github.io/ansible_playbook-baseline-online-server
  topics: ansible, ansible-playbook, bootstrapping
