---
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: |
            (?x)(
                .md|
                .bumpversion.cfg
            )
      - id: end-of-file-fixer
        exclude: ".bumpversion.cfg"
      - id: check-yaml

  - repo: 'https://github.com/pycqa/flake8'
    rev: 7.1.2
    hooks:
      - id: flake8
  - repo: 'https://github.com/adrienverge/yamllint'
    rev: v1.37.0
    hooks:
      - id: yamllint
        args: [-c=./ansible/.yamllint]
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/ansible/ansible-lint
    rev: v25.1.3
    hooks:
      - id: ansible-lint
        args: ["-c=./ansible/.ansible-lint", "--project-dir=./ansible"]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.4
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
