---
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ".md"
      - id: end-of-file-fixer
      - id: check-yaml
      - id: flake8
  - repo: 'https://github.com/adrienverge/yamllint'
    rev: v1.16.0
    hooks:
      - id: yamllint
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.2.0
    hooks:
      - id: seed-isort-config
        args: [--application-directories, "test:."]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
      - id: black
        args: [--safe]
        language_version: python3.6
