---
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        exclude: |
            (?x)(
                .md|
                .bumpversion.cfg
            )
      - id: end-of-file-fixer
        exclude: ".bumpversion.cfg"
      - id: check-yaml

  - repo: 'https://gitlab.com/pycqa/flake8'
    rev: 3.8.3
    hooks:
      - id: flake8
  - repo: 'https://github.com/adrienverge/yamllint'
    rev: v1.24.2
    hooks:
      - id: yamllint
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.4.2
    hooks:
      - id: isort
  - repo: https://github.com/ansible/ansible-lint
    rev: v4.2.0
    hooks:
      - id: ansible-lint
        args: [-x, "306"]  # faild for geerlingguy.docker (Shells that use pipes should set the pipefail option)
        exclude: ".circleci/config.yml"
