---

- include_role:
    name: ypsman.sshd_config
  tags:
    - harder_sshd

- name: "set addition sshd config attributes"
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    validate: 'sshd -t -f %s'
  with_items:
    - {regexp: "^Protocol", line: "Protocol 2"}
    - {regexp: "^StrictModes", line: "StrictModes yes"}
    - {regexp: "^AllowUsers", line: "AllowUsers {{ sshd_AllowUsers | unique | join(' ') }}"}
    - {regexp: "^MaxAuthTries", line: "MaxAuthTries {{ sshd_MaxAuthTries }}"}
  notify: restart sshd
  tags:
    - harder_sshd
