---

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: install common packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ common_packages }}"
