---
# https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#installing-collections
collections:
  # https://github.com/ericsysmin/ansible-collection-system
  - name: ericsysmin.system
roles:
  - name: arillso.logrotate
  - name: geerlingguy.docker
    version: 3.1.1
  - name: geerlingguy.pip
  - name: paulfantom.restic
  - name: robertdebock.fail2ban
  - name: ypsman.sshd_config
  - src: https://gitlab.com/nolte-collection-v2/modules/ansible-roles/ansible_role-k8s-firewalld.git
    # https://github.com/FlatKey/ansible-firewalld-role.git
    version: master
    scm: git
    name: nolte.firewalld-k8s