---
- name: Ensure botocore and boto3 modules are installed
  pip:
    name:
      - "boto3"
      - "botocore"

- name: Using External Role to install all required tools for doing backups
  include_role:
    name: arillso.restic
