---
dependency:
  name: galaxy
  options:
    role-file: ./requirements.yml

platforms:
  - name: molecule-instance-1

provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../inventory/group_vars/
  playbooks:
    converge: ../../master-configure-system.yml
  lint:
    name: ansible-lint
    # enabled: false
    # options:
    #   x:
    #     - ANSIBLE0006
    #     - ANSIBLE0010
    #     - ANSIBLE0011
    #     - ANSIBLE0016
scenario:
  name: default
  test_sequence:
    - lint

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
