---
- name: install the nginx rpm from a remote repo
  yum:
    name: yum-utils
    state: present

- name: install the nginx rpm from a remote repo
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: present

- package:
    name: "{{ item }}"
  with_items:
    - python36u
    - python36u-libs
    - python36u-devel
    - python36u-pip
    - python-pip

- name: install virtualenv
  pip:
    name:
      - "virtualenv"
