---
dependency:
  name: galaxy
  options:
    role-file: ../../roles/requirements.yml

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: instance
    box: generic/centos8
#  - name: instance-ubu
#    # 20.10
#    box: ubuntu/groovy64
    groups:
      - dockerbased
  - name: instance-lts
    # 20.04 lts
    box: ubuntu/focal64
    groups:
      - dockerbased    
#    instance_raw_config_args:
#      - "vm.network 'forwarded_port', guest: 80, host: 8088"

provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../inventory/group_vars/
  playbooks:
    converge: ../../master-configure-system.yml
  lint:
    name: ansible-lint
    # enabled: false
    # options:
    #   x:
    #     - ANSIBLE0006
    #     - ANSIBLE0010
    #     - ANSIBLE0011
    #     - ANSIBLE0016
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - destroy

#scenario:
#  name: default
#  test_sequence:
#    - lint
#
#lint: |
#  set -e
#  yamllint .
#  ansible-lint
#  flake8
