---
- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart firewalld
  service:
    name: firewalld
    state: restarted

- name: started auditd
  systemd:
    state: started
    name: auditd
