---
- hosts: all
  become: true
  vars:
    # oscap_profile: xccdf_org.ssgproject.content_profile_pci-dss
    oscap_profile: xccdf_org.ssgproject.content_profile_standard
    oscap_policy: ssg-centos7-ds
    # scap_profile: xccdf_org.ssgproject.content_profile_stig-java-upstream
    # scap_policy: ssg-jre-ds
    oscap_policy_report_dest: "{{ playbook_dir }}/generated_reports/oscap-reports/{{ inventory_hostname }}-{{ oscap_policy }}.html"
  tasks:

    - name: install openscap scanner
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - openscap-scanner
        - scap-security-guide

    - block:
        - name: run openscap
          command: oscap xccdf eval \
            --profile {{ oscap_profile }} \
            --results-arf /tmp/oscap-arf.xml \
            --report /tmp/oscap-report.html \
            --fetch-remote-resources \
            /usr/share/xml/scap/ssg/content/{{ oscap_policy }}.xml

      always:
        - name: download report
          fetch:
            src: /tmp/oscap-report.html
            dest: "{{ oscap_policy_report_dest }}"
            flat: true
